[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterInterLinks = "d12716ef-a0f6-4df4-a9f1-a5a34e75c656"
NSDEBase = "5aa61ba9-7752-4810-b2ec-484f26c3f007"
NSDETimeParallel = "589f7035-6b7a-40e5-abe3-32909204d25a"

[compat]
Documenter = "1"
DocumenterInterLinks = "1"

[sources.NSDEBase]
rev = "master"
url = "https://github.com/giancarloantonucci/NSDEBase.jl"

[sources.NSDETimeParallel]
rev = "master"
url = "https://github.com/giancarloantonucci/NSDETimeParallel.jl"
